<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Piece.Core.Abstractions</PackageId>
    <Version>0.0.1</Version>
    <Description>Core abstractions for the Piece framework.</Description>
  </PropertyGroup>

</Project>
