<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeTarget>ral_opengl</NativeTarget>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Piece.OpenGL</PackageId>
    <Version>0.0.1</Version>
    <Description>OpenGL rendering integration for the Piece framework.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Piece.Core" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration) == 'Debug'">
    <NativeLibraryDependency Include="glfw3" />
    <NativeLibraryDependency Include="fmtd" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration) == 'Release'">
    <NativeLibraryDependency Include="glfw3" />
    <NativeLibraryDependency Include="fmt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <Import Project="../build/NativeDependencies.targets"/>

</Project>