<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeTarget>piece_core</NativeTarget>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Piece.Core</PackageId>
    <Version>0.0.1</Version>
    <Description>Core functionality for the Piece framework.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Piece.Core.Abstractions" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
  </ItemGroup>

  <Import Project="../build/NativeDependencies.targets"/>

</Project>
