<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Piece.Framework</PackageId>
    <Version>0.0.1</Version>
    <Description>Framework for the Piece engine.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Piece.Core.Abstractions\Piece.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
