# Handles runtime dependency propagation for executable targets
function(enable_runtime_dependencies target)
    if(WIN32)
        get_target_property(_target_type ${target} TYPE)
        if(NOT (_target_type STREQUAL "EXECUTABLE" OR _target_type STREQUAL "MODULE_LIBRARY"))
            message(WARNING "enable_runtime_dependencies: Target '${target}' is not an executable or module library, skipping.")
            return()
        endif()

        # Get the destination directory for runtime dependencies
        get_target_property(_destination_dir ${target} RUNTIME_OUTPUT_DIRECTORY)
        if(NOT _destination_dir)
            set(_destination_dir "$<TARGET_FILE_DIR:${target}>")
        endif()

        # Generate a unique script name for this target's runtime DLL copying
        set(_script_file "${CMAKE_CURRENT_BINARY_DIR}/${target}_copy_runtime_dlls.cmake")

        # Use file(GENERATE) to create a CMake script whose content includes generator expressions.
        # These generator expressions will be evaluated when the generated script is processed (at build time).
        file(GENERATE OUTPUT "${_script_file}" CONTENT "
            # This script is generated by enable_runtime_dependencies for target '${target}'
            # to copy its runtime DLLs.

            set(DLLS \"\$<TARGET_RUNTIME_DLLS:${target}>\") # The '$' needs to be escaped so GENERATE doesn't evaluate it now
            
            # Split the semicolon-separated string into a CMake list
            string(REPLACE \";\" \";\" DLLS_LIST \"\${DLLS}\")

            foreach(DLL_PATH IN LISTS DLLS_LIST)
                if(EXISTS \"\${DLL_PATH}\")
                    message(STATUS \"Copying runtime DLL: \${DLL_PATH} to ${_destination_dir}\")
                    file(COPY \"\${DLL_PATH}\" DESTINATION \"${_destination_dir}\") # No COPY_ONLY
                else()
                    message(WARNING \"enable_runtime_dependencies: Runtime DLL '\${DLL_PATH}' not found for target '${target}', skipping copy.\")
                endif()
            endforeach()
        ")

        # Add a custom command to execute this generated script after the target is built
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -P "${_script_file}"
            COMMENT "Copying runtime DLLs for target '${target}'"
        )
    endif()
endfunction()
